import { Head, useForm } from '@inertiajs/react';
import { conceptQuestions } from '@/lib/curriculum-routes';
import { questions } from '@/lib/curriculum-routes';
import { PageHeader, PageShell } from '@/components/page-shell';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';

type Choice = { id?: number; content: string; is_correct: boolean };
type Question = { id: number; prompt: string; explanation: string | null; difficulty: 'easy' | 'medium' | 'hard'; choices: Choice[] };

export default function QuestionForm({ concept, question }: { concept: { id: number; title: string }; question?: Question }) {
    const form = useForm<{ prompt: string; explanation: string; difficulty: 'easy' | 'medium' | 'hard'; choices: Choice[] }>({ prompt: question?.prompt ?? '', explanation: question?.explanation ?? '', difficulty: question?.difficulty ?? 'medium', choices: question?.choices ?? [{ content: '', is_correct: true }, { content: '', is_correct: false }] });
    const submit = (event: React.FormEvent) => { event.preventDefault(); if (question) { form.put(questions.update(question).url); } else { form.post(conceptQuestions.store(concept).url); } };
    const setChoice = (index: number, field: keyof Choice, value: string | boolean) => form.setData('choices', form.data.choices.map((choice, choiceIndex) => choiceIndex === index ? { ...choice, [field]: value } : field === 'is_correct' && value === true ? { ...choice, is_correct: false } : choice));

    return <PageShell><Head title={question ? 'Edit question' : 'New question'} /><PageHeader eyebrow={concept.title} title={question ? 'Edit question' : 'New question'} description="Create a multiple-choice question with exactly one correct answer." /><Card><CardContent className="pt-6"><form onSubmit={submit} className="grid w-full gap-5"><label className="grid gap-2 text-sm font-medium">Prompt<textarea value={form.data.prompt} onChange={(event) => form.setData('prompt', event.target.value)} className="min-h-28 w-full rounded-md border border-input bg-background p-3" required /></label><label className="grid gap-2 text-sm font-medium">Difficulty<select value={form.data.difficulty} onChange={(event) => form.setData('difficulty', event.target.value as 'easy' | 'medium' | 'hard')} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><label className="grid gap-2 text-sm font-medium">Explanation<textarea value={form.data.explanation} onChange={(event) => form.setData('explanation', event.target.value)} className="min-h-24 w-full rounded-md border border-input bg-background p-3" /></label><fieldset className="grid gap-3"><legend className="text-sm font-medium">Answer choices</legend>{form.data.choices.map((choice, index) => <div key={index} className="flex flex-col gap-3 rounded-lg border p-3 sm:flex-row sm:items-center"><input value={choice.content} onChange={(event) => setChoice(index, 'content', event.target.value)} placeholder={`Choice ${index + 1}`} className="h-9 min-w-0 flex-1 rounded-md border border-input bg-background px-3 text-sm" required /><label className="flex items-center gap-2 text-sm"><input type="radio" checked={choice.is_correct} onChange={() => setChoice(index, 'is_correct', true)} />Correct answer</label></div>)}</fieldset><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={() => form.setData('choices', [...form.data.choices, { content: '', is_correct: false }])}>Add choice</Button><Button disabled={form.processing}>{form.processing ? 'Saving…' : 'Save question'}</Button></div></form></CardContent></Card></PageShell>;
}
