import { Head, useForm } from '@inertiajs/react';
import { concepts, subjectConcepts, topicConcepts } from '@/lib/curriculum-routes';
import { PageHeader, PageShell } from '@/components/page-shell';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';

export default function ConceptForm({ concept, subjects, topics, contextSubject, contextTopic }: { concept?: { id: number; subject_id: number; syllabus_topic_id: number | null; code: string; title: string; description: string | null; sort_order: number }; subjects: { id: number; name: string; code: string }[]; topics: { id: number; subject_id: number; title: string }[]; contextSubject?: { id: number } | null; contextTopic?: { id: number } | null }) {
    const form = useForm({ subject_id: concept?.subject_id ?? contextSubject?.id ?? subjects[0]?.id ?? 0, syllabus_topic_id: concept?.syllabus_topic_id ?? contextTopic?.id ?? null as number | null, code: concept?.code ?? '', title: concept?.title ?? '', description: concept?.description ?? '', sort_order: concept?.sort_order ?? 0 });
    const submit = (event: React.FormEvent) => { event.preventDefault(); if (concept) { form.put(concepts.update(concept).url); } else { form.post(contextTopic ? topicConcepts.store(contextTopic).url : contextSubject ? subjectConcepts.store(contextSubject).url : concepts.store().url); } };

    return <PageShell><Head title={concept ? 'Edit concept' : 'New concept'} /><PageHeader eyebrow="Curriculum administration" title={concept ? 'Edit concept' : 'New concept'} description="Define the teachable unit that connects lessons and assessments." /><Card><CardContent className="pt-6"><form onSubmit={submit} className="grid w-full gap-5 lg:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Subject<select value={form.data.subject_id} onChange={(event) => form.setData('subject_id', Number(event.target.value))} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm">{subjects.map((subject) => <option key={subject.id} value={subject.id}>{subject.code} — {subject.name}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Syllabus topic<select value={form.data.syllabus_topic_id ?? ''} onChange={(event) => form.setData('syllabus_topic_id', event.target.value ? Number(event.target.value) : null)} className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">No syllabus topic</option>{topics.filter((topic) => topic.subject_id === form.data.subject_id).map((topic) => <option key={topic.id} value={topic.id}>{topic.title}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Code<Input value={form.data.code} onChange={(event) => form.setData('code', event.target.value)} required /></label><label className="grid gap-2 text-sm font-medium">Title<Input value={form.data.title} onChange={(event) => form.setData('title', event.target.value)} required /></label><label className="grid gap-2 text-sm font-medium lg:col-span-2">Description<textarea value={form.data.description} onChange={(event) => form.setData('description', event.target.value)} className="min-h-32 w-full rounded-md border border-input bg-background p-3" /></label><div className="lg:col-span-2"><Button disabled={form.processing}>{form.processing ? 'Saving…' : 'Save concept'}</Button></div></form></CardContent></Card></PageShell>;
}
